<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>co</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>Cosima</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(nil|true|false)\b(?![?!])</string>
			<key>name</key>
			<string>constant.language.ruby</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ruby</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^[ \t]+)?(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.context</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[-+]?\d+(\.\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.context</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|elsif|else|while|for|return|self|super|do|end|yield)\b</string>
			<key>name</key>
			<string>keyword.control.context</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;&lt;([A-Z_]+)\n</string>
			<key>end</key>
			<string>^\1</string>
			<key>name</key>
			<string>string.multiline.context</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(and|not|or)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.context</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.context</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.context</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.context</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:\w+(.\w+)*</string>
			<key>name</key>
			<string>support.symbol.context</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Char|Int|UInt|Long|ULong|Float|Double|Context|Pointer|Type|Bool)\b</string>
			<key>name</key>
			<string>support.core-types.context</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.context</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+\??)\(</string>
			<key>name</key>
			<string>meta.function.context</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\.)\w+\b(?!\()</string>
			<key>name</key>
			<string>variable.context</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.co</string>
	<key>uuid</key>
	<string>D5FBE106-1167-496A-93D6-96F52C15AD1E</string>
</dict>
</plist>
